name: nnet_compare
channels:
  - sebp
  - defaults
dependencies:
  - _pytorch_select=1.1.0=cpu
  - _tflow_select=2.2.0=eigen
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - ca-certificates=2020.1.1=0
  - cachetools=3.1.1=py_0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cvxopt=1.2.3=py37h91a2903_1
  - cvxpy=1.0.29=py37_0
  - cvxpy-base=1.0.29=py37h6538335_0
  - cycler=0.10.0=py37_0
  - dill=0.3.1.1=py37_0
  - ecos=2.0.7.post1=py37h259a8f7_2
  - fastcache=1.1.0=py37he774522_0
  - freetype=2.9.1=ha9979f8_1
  - future=0.18.2=py37_0
  - gast=0.2.2=py37_0
  - glpk=4.65=hdc00fd2_2
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37h351948d_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.9=py_1
  - intel-openmp=2020.1=216
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - keras=2.3.1=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37h74a9793_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.4=h7bd577a_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - multiprocess=0.70.8=py37hfa6e2cd_0
  - ninja=1.9.0=py37h74a9793_0
  - numexpr=2.7.1=py37h25d0782_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - osqp=0.5.0=py37h259a8f7_2
  - pandas=1.0.3=py37h47e9c7a_0
  - pip=20.0.2=py37_3
  - protobuf=3.11.4=py37h33f27b4_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pysocks=1.7.1=py37_0
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=cpu_py37h9f948e0_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37he774522_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.23.0=py37_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-learn=0.22.1=py37h6288b17_0
  - scikit-survival=0.12.0=py37he350917_1
  - scipy=1.4.1=py37h9439919_0
  - scs=2.1.1.2=py37h259a8f7_4
  - setuptools=46.2.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h2a8f88b_1
  - tensorboard=2.1.0=py3_0
  - tensorflow=2.1.0=eigen_py37hd727fc0_0
  - tensorflow-base=2.1.0=eigen_py37h49b2757_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - termcolor=1.1.0=py37_1
  - tornado=6.0.4=py37he774522_1
  - tzlocal=2.0.0=py37_0
  - urllib3=1.25.8=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - werkzeug=0.14.1=py37_0
  - wheel=0.34.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.12.1=py37he774522_1
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - feather-format==0.4.1
    - llvmlite==0.32.1
    - numba==0.49.1
    - pyarrow==0.17.0
    - pycox==0.2.1
    - sklearn-pandas==1.8.0
    - torchtuples==0.2.0

